apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: asia-south1-docker.pkg.dev/fast-ability-439911-u1/react-app/backend-app:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        # livenessProbe:                  # Liveness probe
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # readinessProbe:                # Readiness probe
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 3
        #   periodSeconds: 5
